### PR TITLE
Add PHP 8.0 build

### PR DESCRIPTION
**Pull request by andrewmy**
Tried this with enqueue, appears to work.﻿

### CODE REVIEW

**Comment by andrewmy** [comment]
@makasim whenever you get to this please also publish the new tag to Docker Hub 🙌

**Comment by makasim** [comment]
I have access to this repo.

**Comment by makasim** [comment]
Can you add it here https://github.com/makasim/docker-nginx-php-fpm ?

**Comment by andrewmy** [comment]
Added as https://github.com/makasim/docker-nginx-php-fpm/pull/2
Does it also mean a different docker hub namespace?

**Comment by makasim** [comment]
Sure, https://hub.docker.com/repository/docker/makasim/nginx-php-fpm

**Pull request closed without merging**
